### ISSUE TITLE
spring boot starter parent

### ISSUE THREAD

**Issue by greyfox33** [jbarrez/spring-boot-with-activiti-example#6]
I think the maven dependancy on the spring boot starter parent (1.3.0.RC1) should be changed to 1.3.0.RELEASE. Maven could not find 1.3.0.RC1 from Eclipse for me.

**Comment by jbarrez** [comment]
Indeed. Done: https://github.com/jbarrez/spring-boot-with-activiti-example/commit/16faedc511679b03760814af8e9bbb07277ba344
